In [2]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Mayank", "Himanshu", "Karan", "Rahul", "Aman", "Vikas"],
    "Age": [20, 22, np.nan, 25, 21, 18],
    "City": ["Delhi", "Mumbai", "Pune", np.nan, "Jaipur", "Dehradun"],
    "Salary": [50000, 60000, 45000, 70000, np.nan, 40000]
}

df = pd.DataFrame(data)
df

       Name   Age      City   Salary
0    Mayank  20.0     Delhi  50000.0
1  Himanshu  22.0    Mumbai  60000.0
2     Karan   NaN      Pune  45000.0
3     Rahul  25.0       NaN  70000.0
4      Aman  21.0    Jaipur      NaN
5     Vikas  18.0  Dehradun  40000.0

In [ ]:
# to fill all nan with specific values

df.fillna(0)  

#NOTE --> this will not change it in original datauntil we write inplace = true.

       Name   Age      City   Salary
0    Mayank  20.0     Delhi  50000.0
1  Himanshu  22.0    Mumbai  60000.0
2     Karan   0.0      Pune  45000.0
3     Rahul  25.0         0  70000.0
4      Aman  21.0    Jaipur      0.0
5     Vikas  18.0  Dehradun  40000.0

In [7]:
#to fill with our given values

values = {"Name" : "Nothing"  , "Age": 20, "City":"UNKNOWN" , "Salary":1}
df.fillna(value=values)

       Name   Age      City   Salary
0    Mayank  20.0     Delhi  50000.0
1  Himanshu  22.0    Mumbai  60000.0
2     Karan  20.0      Pune  45000.0
3     Rahul  25.0   UNKNOWN  70000.0
4      Aman  21.0    Jaipur      1.0
5     Vikas  18.0  Dehradun  40000.0

In [ ]:
# to fill with the mean of all data points
# df.fillna(df.mean())