In [1]:
import numpy as np
import pandas as pd

data = {
    "Name": ["Mayank", "Himanshu", "Karan", "Rahul", "Aman", "Vikas"],
    "Age": [20, 22, np.nan, 25, 21, 18],
    "City": ["Delhi", "Mumbai", "Pune", np.nan, "Jaipur", "Dehradun"],
    "Salary": [50000, 60000, 45000, 70000, np.nan, 40000]
}

df = pd.DataFrame(data)
df

       Name   Age      City   Salary
0    Mayank  20.0     Delhi  50000.0
1  Himanshu  22.0    Mumbai  60000.0
2     Karan   NaN      Pune  45000.0
3     Rahul  25.0       NaN  70000.0
4      Aman  21.0    Jaipur      NaN
5     Vikas  18.0  Dehradun  40000.0

In [2]:
# If you want to remove whole row if it contain null value

df.dropna()

       Name   Age      City   Salary
0    Mayank  20.0     Delhi  50000.0
1  Himanshu  22.0    Mumbai  60000.0
5     Vikas  18.0  Dehradun  40000.0

In [ ]:
# if you want to remove only that row which atleast some non null values

df.dropna(thresh=4) #Should contain atleast 4 non null values.

       Name   Age      City   Salary
0    Mayank  20.0     Delhi  50000.0
1  Himanshu  22.0    Mumbai  60000.0
5     Vikas  18.0  Dehradun  40000.0

In [ ]:
# drop --> row wise things are done