In [2]:
import numpy as np
import pandas as pd

employee = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104],
    "Name": ["Mayank", "Himanshu", "Karan", "Rahul"],
    "Department": ["IT", "HR", "Finance", "IT"]
})

salary = pd.DataFrame({
    "Employee_ID": [103, 104, 105, 106],
    "Salary": [55000, 70000, 45000, 60000]
})

employee

   Employee_ID      Name Department
0          101    Mayank         IT
1          102  Himanshu         HR
2          103     Karan    Finance
3          104     Rahul         IT

In [3]:
salary

   Employee_ID  Salary
0          103   55000
1          104   70000
2          105   45000
3          106   60000

In [5]:
# Merging both

pd.merge(employee,salary , on="Employee_ID") #we should also give on parameter to tell him on which column basic we have to merge

   Employee_ID   Name Department  Salary
0          103  Karan    Finance   55000
1          104  Rahul         IT   70000

In [ ]:
pd.merge(employee,salary,on="Employee_ID",how="inner")

#BY default how is always set to inner just give common between both

   Employee_ID   Name Department  Salary
0          103  Karan    Finance   55000
1          104  Rahul         IT   70000

In [ ]:
pd.merge(employee,salary,on="Employee_ID",how="outer")

# outer --> It will give both tables value and the unknown value will be filled with nan

   Employee_ID      Name Department   Salary
0          101    Mayank         IT      NaN
1          102  Himanshu         HR      NaN
2          103     Karan    Finance  55000.0
3          104     Rahul         IT  70000.0
4          105       NaN        NaN  45000.0
5          106       NaN        NaN  60000.0

In [ ]:
pd.merge(employee,salary,on="Employee_ID",how="left")

# left --> Will give me the values (Employee_Id)  based on the employee table ,all Emp_id will be there

   Employee_ID      Name Department   Salary
0          101    Mayank         IT      NaN
1          102  Himanshu         HR      NaN
2          103     Karan    Finance  55000.0
3          104     Rahul         IT  70000.0

In [9]:
pd.merge(employee,salary,on="Employee_ID",how="right")

   Employee_ID   Name Department  Salary
0          103  Karan    Finance   55000
1          104  Rahul         IT   70000
2          105    NaN        NaN   45000
3          106    NaN        NaN   60000

In [ ]:
# right --> Will give me the values (Employee_Id)  based on the salary table ,all Emp_id will be there .