In [5]:
import numpy as np
import pandas as pd

data = [
    ["Mayank", 20, "Delhi", 50000],
    ["Himanshu", 22, "Mumbai", 60000],
    ["Karan", 19, "Pune", 45000],
    ["Rahul", 25, "Chandigarh", 70000],
    ["Aman", 21, "Jaipur", 55000],
    ["Vikas", 18, "Dehradun", 40000]
]

columns = ["Name","Age","City","Salary"]

p = pd.DataFrame(data,columns=columns)
p

       Name  Age        City  Salary
0    Mayank   20       Delhi   50000
1  Himanshu   22      Mumbai   60000
2     Karan   19        Pune   45000
3     Rahul   25  Chandigarh   70000
4      Aman   21      Jaipur   55000
5     Vikas   18    Dehradun   40000

In [6]:
# I ONLY WANT TO SEE THOSE PEOPLE WHOSE AGE IS ABOVE 20

p[p["Age"]>20]

       Name  Age        City  Salary
1  Himanshu   22      Mumbai   60000
3     Rahul   25  Chandigarh   70000
4      Aman   21      Jaipur   55000

In [8]:
# I ONLY WANT TO SEE PEOPLE WHOSE AGE IS ABOVE 20 AND THEIR CITY  MUST BE MUMBAI
p[(p["Age"]>20) & (p["City"]=='Mumbai')]

       Name  Age    City  Salary
1  Himanshu   22  Mumbai   60000