In [1]:
import numpy as np
import pandas as pd

data = [
    ["Mayank", 20, "Delhi", 50000],
    ["Himanshu", 22, "Mumbai", 60000],
    ["Karan", 21, "Pune", 55000]
]

column = ["Name" , "Age", "City" ,"Salary"]
d = pd.DataFrame(data,columns=column)

In [2]:
# Inserting new Column

d["Designation"] = ["Engineer" , "Engineer" ,"Cricketer"]
d

       Name  Age    City  Salary Designation
0    Mayank   20   Delhi   50000    Engineer
1  Himanshu   22  Mumbai   60000    Engineer
2     Karan   21    Pune   55000   Cricketer

In [ ]:
# Removing new Column

# d.drop("Designation") #It will give error because by default axis = 0 and it is finding it in row 0,1,2 etc so we have to give axis = 1 so that it can find it in columns

d.drop("Designation",axis=1)

# It will just show us how after removal our data will look means does not delete it from d permanently when u print u will still see .

       Name  Age    City  Salary
0    Mayank   20   Delhi   50000
1  Himanshu   22  Mumbai   60000
2     Karan   21    Pune   55000

In [ ]:
# So to encounter above problem we use inline = true 
d.drop("Designation",axis=1,inplace=True)

In [ ]:
# WE can also drop multiple things also

d.drop(["Salary" , "City"] , axis=1)

       Name  Age
0    Mayank   20
1  Himanshu   22
2     Karan   21

In [ ]:
#we can also remove row
d.drop(0,axis=0)

       Name  Age    City  Salary
1  Himanshu   22  Mumbai   60000
2     Karan   21    Pune   55000