In [1]:
# When we combine multiple series together than it become an dataFrame

In [ ]:
# Creation of data frames
import numpy as np
import pandas as pd

# from dictionary
data = {
    "Name": ["Mayank", "Himanshu", "Karan"],
    "Age": [20, 22, 21],
    "City": ["Delhi", "Mumbai", "Pune"],
    "Salary": [50000, 60000, 55000]
}

pd.DataFrame(data)

       Name  Age    City  Salary
0    Mayank   20   Delhi   50000
1  Himanshu   22  Mumbai   60000
2     Karan   21    Pune   55000

In [4]:
# from lists
data = [
    ["Mayank", 20, "Delhi", 50000],
    ["Himanshu", 22, "Mumbai", 60000],
    ["Karan", 21, "Pune", 55000]
]

pd.DataFrame(data) #Here no column are given so it will take it defaulty as 0,1,2

          0   1       2      3
0    Mayank  20   Delhi  50000
1  Himanshu  22  Mumbai  60000
2     Karan  21    Pune  55000

In [5]:
# we can also give column in lists
data = [
    ["Mayank", 20, "Delhi", 50000],
    ["Himanshu", 22, "Mumbai", 60000],
    ["Karan", 21, "Pune", 55000]
]

column = ["Name" , "Age", "City" ,"Salary"]
d = pd.DataFrame(data,columns=column)
print(d)

       Name  Age    City  Salary
0    Mayank   20   Delhi   50000
1  Himanshu   22  Mumbai   60000
2     Karan   21    Pune   55000