In [2]:
# IN THIS WE ARE SELECTING A PORTION FROM ROWS AND COLUMN
import numpy as np
import pandas as pd
data = [
    ["Mayank", 20, "Delhi", 50000],
    ["Himanshu", 22, "Mumbai", 60000],
    ["Karan", 21, "Pune", 55000]
]

column = ["Name" , "Age", "City" ,"Salary"]
d = pd.DataFrame(data,columns=column)
d

       Name  Age    City  Salary
0    Mayank   20   Delhi   50000
1  Himanshu   22  Mumbai   60000
2     Karan   21    Pune   55000

In [4]:
d.loc[[0,1]][["City","Salary"]]

     City  Salary
0   Delhi   50000
1  Mumbai   60000

In [5]:
d.loc[[1,2]][["Name","Age"]]

       Name  Age
1  Himanshu   22
2     Karan   21