In [2]:
import numpy as np
import pandas as pd

data = [
    ["Mayank", 20, "Delhi", 50000],
    ["Himanshu", 22, "Mumbai", 60000],
    ["Karan", 21, "Pune", 55000]
]

column = ["Name" , "Age", "City" ,"Salary"]
d = pd.DataFrame(data,columns=column)
d

       Name  Age    City  Salary
0    Mayank   20   Delhi   50000
1  Himanshu   22  Mumbai   60000
2     Karan   21    Pune   55000

In [ ]:
# d[0] Will give error because here indexing is done with columns name

d["Name"]  #Will display Name column
d["Age"]  #will display age series or column

0    20
1    22
2    21
Name: Age, dtype: int64

In [ ]:
# If you want to acess two columns by giving list of list
d[["Name","Salary"]]

       Name  Salary
0    Mayank   50000
1  Himanshu   60000
2     Karan   55000