In [1]:
# You can select the rows using loc and iloc (index location)
import numpy as np
import pandas as pd

data = [
    ["Mayank", 20, "Delhi", 50000],
    ["Himanshu", 22, "Mumbai", 60000],
    ["Karan", 21, "Pune", 55000]
]

column = ["Name" , "Age", "City" ,"Salary"]
d = pd.DataFrame(data,columns=column)

In [ ]:
#d[0] #Will give You error beacuse in pandas we use loc and iloc

d.loc[0]
d.loc[[0,1]] #acessing both

       Name  Age    City  Salary
0    Mayank   20   Delhi   50000
1  Himanshu   22  Mumbai   60000

In [7]:
d.iloc[0] #based on index (used when somebody gives labels according to himself)
d.iloc[[0,1]]

       Name  Age    City  Salary
0    Mayank   20   Delhi   50000
1  Himanshu   22  Mumbai   60000