In [6]:
import numpy as np
import pandas as pd

import numpy as np
import pandas as pd

df1 = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [2]:
# We can also apply functions to them

def square(x):
    return x**2

In [7]:
df1['B']=df1['B'].apply(square)
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500

In [ ]:
# lambda --> Python me lambda ka use ek small/short function banane ke liye hota hai, bina def likhe.
# Basic syntax
# lambda arguments: expression
# Normal function
# def square(x):
#     return x * x


# print(square(5))
# Same kaam with lambda
# square = lambda x: x * x


# print(square(5))

In [ ]:
# we can also use lamda 


df1['A'].apply(lambda x : x**2)

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64